name             'rhodecode'
maintainer       'Ryan Hass'
maintainer_email 'ryan underscore hass a t rapid7 d o t com'
license          'Apache 2.0'
description      'Installs/Configures RhodeCode'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.2.0'

depends          'apt'
depends          'database', '>= 3.0.0'
depends          'git'
depends          'nginx'
depends          'openssl'
depends          'postgresql'
depends          'python', '>= 1.4.6'
depends          'rabbitmq'
